# .github/workflows/azure-app-service.yml

name: Build and Deploy Next.js to Azure App Service

# Controls when the action will run.
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production # Optional: For environment-specific secrets/rules

    steps:
      # ------------------------------------------------------------------
      # 1. CHECKOUT CODE
      #    Gets a copy of your repository on the runner machine.
      # ------------------------------------------------------------------
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      # ------------------------------------------------------------------
      # 2. SETUP NODE.JS
      #    Installs the specified version of Node.js.
      #    Use the same major version you are using in development and on App Service.
      # ------------------------------------------------------------------
      - name: 'Set up Node.js version'
        uses: actions/setup-node@v4
        with:
          node-version: '22.x' # Or '20.x', etc.

      # ------------------------------------------------------------------
      # 3. INSTALL DEPENDENCIES & BUILD
      #    Installs npm packages and runs the Next.js build command.
      #    This creates the optimized production build in the .next folder.
      # ------------------------------------------------------------------
      - name: 'Install dependencies & Build'
        run: |
          npm install
          npm run build
        # For React developers: This is equivalent to creating your production-ready artifacts.

      # ------------------------------------------------------------------
      # 4. DEPLOY TO AZURE APP SERVICE
      #    This action handles authentication and deploys the app.
      #    It knows to deploy the necessary files for a Node.js app.
      # ------------------------------------------------------------------
      - name: 'Deploy to Azure App Service'
        uses: azure/webapps-deploy@v3
        with:
          # Name of your Azure App Service
          app-name: 'gerold' 

          # This is the secret containing your publishing profile.
          # You get this from the Azure portal.
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

          # The action needs to know what to deploy.
          # For a standard Next.js app, this includes the build output, public files,
          # config, and production node_modules.
          package: '.'
